FROM node:20-alpine AS builder

WORKDIR /app

# Добавили слеш в конце назначения (./)
COPY frontend/package*.json ./
RUN npm ci

# Здесь тоже лучше использовать ./ для надежности
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
